version: '3.3'

services:
  jupyter:
    image: $NB_NAME:latest
    container_name: $NB_NAME
    env_file: .env
    build:
      context: ../toxic-comments/docker/jupyter/
      dockerfile: Dockerfile
      args:
        - ML_USER=$ML_USER
        - UID=$UID
        - GID=$GID
        # - WORKSPACE_FOLDER=$WORKSPACE_FOLDER
    ports:
      - "$NB_PORT:8888"
    volumes:
      - ../toxic-comments/config:/home/$ML_USER/$WORKSPACE_FOLDER/$CONFIG_FOLDER
      - ../toxic-comments/data:/home/$ML_USER/$WORKSPACE_FOLDER/$DATA_FOLDER
      - ../toxic-comments/notebook:/home/$ML_USER/$WORKSPACE_FOLDER/$NB_FOLDER
      - ../toxic-comments/src:/home/$ML_USER/$WORKSPACE_FOLDER/$SRC_FOLDER
      - mlflow:/home/$ML_USER/$WORKSPACE_FOLDER/$SAVED_MODELS_FOLDER:rw
    networks:
      - toxic-network
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  mlflow:
    image: mlflow
    container_name: $MLFLOW_NAME
    build:
      context: ../mlflow/docker/
      dockerfile: mlflow.df
    env_file: .env
    ports:
      - "$MLFLOW_PORT:5000"
    volumes:
      - mlflow:$MLRUNS_PATH:rw
    depends_on:
      - postgres
    networks:
      - toxic-network
        
  postgres:
    image: postgres
    container_name: $POSTGRES_NAME
    env_file: .env
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ../mlflow/postgresql/data:/var/lib/postgresql/data
    networks:
      - toxic-network
    environment:
      - POSTGRES_DB=$MLFLOW_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

networks:
  toxic-network:

volumes:
  mlflow:
  postgres:
