version: '3.3'

services:
  jupyter:
    image: $NB_NAME:latest
    container_name: $NB_NAME
    env_file: .env
    build:
      context: ../toxic-comments/docker/
      dockerfile: Dockerfile
      args:
        - ML_USER=$ML_USER
        - UID=$UID
        - GID=$GID
    ports:
      - "$NB_PORT:8888"
    volumes:
      - ${PWD}/../toxic-comments:/home/$ML_USER/workspace
    networks:
      - toxic-network
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  mlflow:
    image: mlflow
    container_name: $MLFLOW_CONTAINER_NAME
    build:
      context: ../mlflow/docker/
      dockerfile: mlflow.df
    env_file: .env
    ports:
      - "$MLFLOW_PORT:5000"
    volumes:
      - ${PWD}/../mlflow/mlruns:$MLRUNS_PATH
    depends_on:
      - postgres
    networks:
      - toxic-network
        
  postgres:
    image: postgres
    container_name: $POSTGRES_NAME
    env_file: .env
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - ${PWD}/../mlflow/postgresql/data:/var/lib/postgresql/data
    networks:
      - toxic-network
    environment:
      - POSTGRES_DB=$MLFLOW_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

networks:
  toxic-network:
